name: Update README with latest YouTube video
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-youtube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest YouTube video
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/pedrofabian"