name: Update README with latest Spotify track
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-spotify:
    name: Update README with latest Spotify track
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch latest Spotify track
        uses: Platane/snk@v3
        with:
          github_user_name: Owono2001
          spotify_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          comment_tag_name: SPOTIFY-TRACK
