name: Update README with latest Spotify track

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-spotify:
    name: Update README with latest Spotify track
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch latest Spotify track
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://owono2001-6yg421j5r-owono2001s-projects.vercel.app/api/spotify"
          max_post_count: 1
          comment_tag_name: SPOTIFY-TRACK