name: Update README with latest YouTube video
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-youtube:
    name: Update README with latest YouTube video
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch latest YouTube video
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbRG9Pk5R-tN-slWhmwXvEw"
          max_post_count: 1
          comment_tag_name: YOUTUBE-VIDEO